import { ArrowRight, Check, Clock3, FileText, Fingerprint, LandPlot, ShieldAlert, UploadCloud } from 'lucide-react';
import { Link } from 'wouter';
import { PageHead, Panel, SectionLabel, StatusBadge } from '@/components/AppShell';
import { demoRecord, stages } from '@/data/mockData';
export function Workspace({ onLoad }: { onLoad: () => void }) {
 return <><PageHead eyebrow="Registry desk / 06 February 2026" title="Land record verification"><button onClick={onLoad} className="bg-[#214f4e] text-[#f7f3eb] px-4 py-2.5 text-sm flex items-center gap-2 hover:bg-[#173e3d]" data-testid="button-load-demo"><Fingerprint size={16}/> Load demo record <ArrowRight size={15}/></button></PageHead>
 <div className="grid lg:grid-cols-[1.4fr_.8fr] gap-5 mb-5">
  <Panel className="p-6 md:p-8 paper-grid"><div className="flex justify-between"><div><SectionLabel>Current examination</SectionLabel><div className="font-mono text-xs text-[#b26337] mt-3">{demoRecord.id}</div><h2 className="font-serif text-3xl mt-1">{demoRecord.ownerName}</h2><p className="text-sm text-[#687571] mt-1">S/o {demoRecord.fatherName} · Survey {demoRecord.surveyNumber} · {demoRecord.village}, {demoRecord.district}</p></div><StatusBadge tone="warn">Officer Review</StatusBadge></div>
   <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-9 pt-5 border-t border-[#d5cdbd]">{[['Extracted area','2.40 acre'],['Database area','2.84 acre'],['Risk score','78 / 100'],['Boundary','Overlap flagged']].map(([a,b])=><div key={a}><SectionLabel>{a}</SectionLabel><p className="font-mono text-sm mt-2">{b}</p></div>)}</div>
  </Panel>
  <Panel className="p-6"><div className="flex items-center justify-between mb-5"><SectionLabel>Pipeline progress</SectionLabel><span className="text-[11px] font-mono text-[#b26337]">05 / 06</span></div><div className="space-y-4">{stages.map((s,i)=><div className="flex items-center gap-3" key={s}><span className={`w-5 h-5 grid place-items-center border ${i<5?'border-[#43736b] bg-[#43736b] text-white':'border-[#b7b9af] text-[#84908a]'}`}>{i<5?<Check size={12}/>:<span className="text-[10px]">{i+1}</span>}</span><span className={`text-sm ${i===5?'font-semibold':''}`}>{s}</span>{i===5&&<span className="ml-auto text-[10px] text-[#b26337]">NEXT</span>}</div>)}</div></Panel>
 </div>
 <div className="grid md:grid-cols-3 gap-5"><Panel className="p-6"><UploadCloud className="text-[#b26337] mb-5" size={22}/><h3 className="font-semibold">Start an examination</h3><p className="text-sm text-[#687571] mt-2 leading-relaxed">Upload a scanned registry document. PDF, JPG and PNG files are supported.</p><Link href="/upload" className="inline-flex items-center gap-2 text-sm text-[#214f4e] font-semibold mt-5" data-testid="link-upload-start">Open upload desk <ArrowRight size={14}/></Link></Panel>
 <Panel className="p-6"><ShieldAlert className="text-[#b26337] mb-5" size={22}/><h3 className="font-semibold">Review the evidence</h3><p className="text-sm text-[#687571] mt-2 leading-relaxed">Three indicators need a human decision before this parcel can be verified.</p><Link href="/risk" className="inline-flex items-center gap-2 text-sm text-[#214f4e] font-semibold mt-5" data-testid="link-risk-review">Open risk assessment <ArrowRight size={14}/></Link></Panel>
 <Panel className="p-6"><Clock3 className="text-[#b26337] mb-5" size={22}/><h3 className="font-semibold">Recent activity</h3><div className="mt-3 text-sm"><div className="flex gap-3 py-2 border-b border-[#e3dccf]"><FileText size={15} className="text-[#73827d] mt-0.5"/><span>OCR extraction completed<small className="block text-xs text-[#89908b] mt-1">06 Feb · 14:32</small></span></div><div className="flex gap-3 py-2"><LandPlot size={15} className="text-[#73827d] mt-0.5"/><span>Boundary check queued<small className="block text-xs text-[#89908b] mt-1">06 Feb · 14:33</small></span></div></div><Link href="/concern" className="inline-flex items-center gap-2 mt-5 text-sm text-[#a65435] font-semibold" data-testid="link-raise-concern">Raise a concern <ArrowRight size={14}/></Link></Panel></div></>;
}